//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.26 at 02:35:07 PM IST 
//

package com.globalpay.ws.ca.generatedb24classes;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.globalpay.ws.ca.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: com.globalpay.ws.ca.jaxb.msgHeader
	 * 
	 */
	public ObjectFactory() {
	}

	
	/**
	 * Create an instance of {@link CurrentConnection }
	 * 
	 */
	public CurrentConnection createCurrentConnection() {
		return new CurrentConnection();
	}

	
	/**
	 * Create an instance of {@link BASE24 }
	 * 
	 */
	public BASE24 createBASE24() {
		return new BASE24();
	}

	/**
	 * Create an instance of {@link BASE24 .MSGHEADER }
	 * 
	 */
	public BASE24.MSGHEADER createBASE24MSGHEADER() {
		return new BASE24.MSGHEADER();
	}

	/**
	 * Create an instance of {@link BASE24 .MSGHEADER.SCCGP }
	 * 
	 */
	public BASE24.MSGHEADER.SCCGP createBASE24MSGHEADERSCCGP() {
		return new BASE24.MSGHEADER.SCCGP();
	}

	/**
	 * Create an instance of {@link BASE24 .MSGHEADER.MCCGP }
	 * 
	 */
	public BASE24.MSGHEADER.MCCGP createBASE24MSGHEADERMCCGP() {
		return new BASE24.MSGHEADER.MCCGP();
	}

	// Base24 Records

	/**
	 * Create an instance of {@link B24RECORDS }
	 * 
	 */
	public B24RECORDS createB24RECORDS() {
		return new B24RECORDS();
	}

	/**
	 * Create an instance of {@link B24RECORDS.PTDFRECORD }
	 * 
	 */
	public B24RECORDS.PTDFRECORD createB24RECORDSPTDFRECORD() {
		return new B24RECORDS.PTDFRECORD();
	}

	/**
	 * Create an instance of {@link B24RECORDS.PTDFRECORD.PTDFRECIMAGE }
	 * 
	 */
	public B24RECORDS.PTDFRECORD.PTDFRECIMAGE createB24RECORDSPTDFRECORDPTDFRECIMAGE() {
		return new B24RECORDS.PTDFRECORD.PTDFRECIMAGE();
	}

	/**
	 * Create an instance of {@link B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF }
	 * 
	 */
	public B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF createB24RECORDSPTDFRECORDPTDFRECIMAGEPTDFDEF() {
		return new B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF();
	}

	/**
	 * Create an instance of
	 * {@link B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.SRVS }
	 * 
	 */
	public B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.SRVS createB24RECORDSPTDFRECORDPTDFRECIMAGEPTDFDEFSRVS() {
		return new B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.SRVS();
	}

	/**
	 * Create an instance of {@link B24RECORDS.PRDFRECORD }
	 * 
	 */
	public B24RECORDS.PRDFRECORD createB24RECORDSPRDFRECORD() {
		return new B24RECORDS.PRDFRECORD();
	}

	/**
	 * Create an instance of {@link B24RECORDS.PRDFRECORD.WSSERVICE }
	 * 
	 */
	public B24RECORDS.PRDFRECORD.WSSERVICE createB24RECORDSPRDFRECORDWSSERVICE() {
		return new B24RECORDS.PRDFRECORD.WSSERVICE();
	}

	/**
	 * Create an instance of {@link B24RECORDS.PRDFRECORD.PRDFRECIMAGE }
	 * 
	 */
	public B24RECORDS.PRDFRECORD.PRDFRECIMAGE createB24RECORDSPRDFRECORDPRDFRECIMAGE() {
		return new B24RECORDS.PRDFRECORD.PRDFRECIMAGE();
	}

	/**
	 * Create an instance of
	 * {@link B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.TERMCITYST }
	 * 
	 */
	public B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.TERMCITYST createB24RECORDSPTDFRECORDPTDFRECIMAGEPTDFDEFTERMCITYST() {
		return new B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.TERMCITYST();
	}

	/**
	 * Create an instance of
	 * {@link B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.TERMOWNER }
	 * 
	 */
	public B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.TERMOWNER createB24RECORDSPTDFRECORDPTDFRECIMAGEPTDFDEFTERMOWNER() {
		return new B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.TERMOWNER();
	}

	/**
	 * Create an instance of
	 * {@link B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.SRVREP }
	 * 
	 */
	public B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.SRVREP createB24RECORDSPTDFRECORDPTDFRECIMAGEPTDFDEFSRVREP() {
		return new B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.SRVREP();
	}

	/**
	 * Create an instance of
	 * {@link B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.TRANSACTIONS }
	 * 
	 */
	public B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.TRANSACTIONS createB24RECORDSPTDFRECORDPTDFRECIMAGEPTDFDEFTRANSACTIONS() {
		return new B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.TRANSACTIONS();
	}

	/**
	 * Create an instance of
	 * {@link B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.STATICRPQFIELDS }
	 * 
	 */
	public B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.STATICRPQFIELDS createB24RECORDSPTDFRECORDPTDFRECIMAGEPTDFDEFSTATICRPQFIELDS() {
		return new B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.STATICRPQFIELDS();
	}

	/**
	 * Create an instance of
	 * {@link B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.SRVS.SRV }
	 * 
	 */
	public B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.SRVS.SRV createB24RECORDSPTDFRECORDPTDFRECIMAGEPTDFDEFSRVSSRV() {
		return new B24RECORDS.PTDFRECORD.PTDFRECIMAGE.PTDFDEF.SRVS.SRV();
	}

	/**
	 * Create an instance of {@link B24RECORDS.PRDFRECORD.WSSERVICE.WSSERVICE1 }
	 * 
	 */
	public B24RECORDS.PRDFRECORD.WSSERVICE.WSSERVICE1 createB24RECORDSPRDFRECORDWSSERVICEWSSERVICE1() {
		return new B24RECORDS.PRDFRECORD.WSSERVICE.WSSERVICE1();
	}

	/**
	 * Create an instance of {@link B24RECORDS.PRDFRECORD.PRDFRECIMAGE.RKEY }
	 * 
	 */
	public B24RECORDS.PRDFRECORD.PRDFRECIMAGE.RKEY createB24RECORDSPRDFRECORDPRDFRECIMAGERKEY() {
		return new B24RECORDS.PRDFRECORD.PRDFRECIMAGE.RKEY();
	}

	/**
	 * Create an instance of {@link B24RECORDS.PRDFRECORD.PRDFRECIMAGE.AKEY }
	 * 
	 */
	public B24RECORDS.PRDFRECORD.PRDFRECIMAGE.AKEY createB24RECORDSPRDFRECORDPRDFRECIMAGEAKEY() {
		return new B24RECORDS.PRDFRECORD.PRDFRECIMAGE.AKEY();
	}

	/**
	 * Create an instance of {@link B24RECORDS.PRDFRECORD.PRDFRECIMAGE.RETAILER }
	 * 
	 */
	public B24RECORDS.PRDFRECORD.PRDFRECIMAGE.RETAILER createB24RECORDSPRDFRECORDPRDFRECIMAGERETAILER() {
		return new B24RECORDS.PRDFRECORD.PRDFRECIMAGE.RETAILER();
	}
	
	//Template

	/**
	 * Create an instance of {@link Templates }
	 * 
	 */
	public Templates createTemplates() {
		return new Templates();
	}

	/**
	 * Create an instance of {@link Templates.PTDF }
	 * 
	 */
	public Templates.PTDF createTemplatesPTDF() {
		return new Templates.PTDF();
	}

	/**
	 * Create an instance of {@link Templates.PRDF }
	 * 
	 */
	public Templates.PRDF createTemplatesPRDF() {
		return new Templates.PRDF();
	}

	/**
	 * Create an instance of {@link Templates.PTDF.Template }
	 * 
	 */
	public Templates.PTDF.Template createTemplatesPTDFTemplate() {
		return new Templates.PTDF.Template();
	}

	/**
	 * Create an instance of {@link Templates.PRDF.Template }
	 * 
	 */
	public Templates.PRDF.Template createTemplatesPRDFTemplate() {
		return new Templates.PRDF.Template();
	}

}
